[package]
name = "vetis"
version = "0.1.6"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Very Tiny Server"
readme = "README.md"
license.workspace = true
keywords = ["http", "networking", "server", "rest-server"]
publish = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.wix]
upgrade-guid = "76DF79DF-E1F9-40A7-89D1-3190562C7851"
path-guid = "FEA82F70-7E57-447F-A361-76FB5E25BA5F"
license = false
eula = false

[features]
default = []

[dependencies]
async-lock = { workspace = true }
bytes =  { workspace = true }
futures-util = { workspace = true }
http =  { workspace = true }
http-body-util =  { workspace = true }
http-serde-ext = "1.0.2"
hyper = { workspace = true, default-features = false, features = ["server"] }
hyper-body-utils = { workspace = true, default-features = false }
log = { workspace = true }
radix_trie = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml_ng = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting"] }
typetag = { workspace = true }
url = { workspace = true }
