[package]
name = "vetis-compio"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Very Tiny Server with compio runtime"
readme = "README.md"
license.workspace = true
keywords = ["http", "networking", "compio", "rest-server"]
publish = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.wix]
upgrade-guid = "76DF79DF-E1F9-40A7-89D1-3190562C7851"
path-guid = "FEA82F70-7E57-447F-A361-76FB5E25BA5F"
license = false
eula = false

[features]
default = [
  "http1",
  "http2",
  #"http3",
  "rust-tls",
]

rust-tls = ["compio-tls/rustls", "rustls-provider"]

rustls-provider = ["__rustls_awc_lc_rs"]
__rustls_awc_lc_rs = ["rustls/aws-lc-rs"]
__rustls_ring = ["rustls/ring"]

http1 = [
  "hyper/http1",
  "hyper/server",
  "hyper-util/server",
  "hyper-util/http1",
  "hyper-body-utils/compio",
]
http2 = [
  "hyper/http2",
  "hyper/server",
  "hyper-util/server",
  "hyper-util/http2",
  "hyper-body-utils/compio",
]
http3 = [
  "compio-quic/h3",
  "compio-quic/ring",
  "hyper/server",
  "hyper-util/server",
  "hyper-body-utils/compio",
  "hyper-body-utils/compio-h3",
]

[dependencies]
async-lock = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
compio-quic = { version = "0.8.2", default-features = false, optional = true }
compio-tls = { version = "0.10.0", default-features = false, optional = true }
cyper-core = "0.9.0"
env_logger = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, optional = true }
hyper-body-utils = { workspace = true, default-features = false, optional = true }
hyper-util = { workspace = true, optional = true }
log = { workspace = true }
radix_trie = { workspace = true }
rand = { workspace = true }
rustls = { workspace = true, optional = true }
send_wrapper = { version = "0.6.0", default-features = false }
serde = { workspace = true }
serde_yaml_ng = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
typetag = { workspace = true }
url = { workspace = true }
vetis = { workspace = true, default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
compio = { version = "0.19.2", features = [
  "fs",
  "io",
  "net",
  "macros",
  "io-uring",
  "runtime",
  "signal",
  "tls",
], default-features = false }

[target.'cfg(all(unix, not(target_os = "linux")))'.dependencies]
compio = { version = "0.19.2", features = [
  "fs",
  "io",
  "net",
  "macros",
  "polling",
  "runtime",
  "signal",
  "tls",
], default-features = false }

[dev-dependencies]
deboa = { workspace = true }
deboa-compio = { version = "0.1.1", features = [
  "http1",
  "http2",
  #"http3",
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
], default-features = false }
vetis-macros = { workspace = true }
