[package]
name = "vetis-smol"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Very Tiny Server with smol runtime"
readme = "README.md"
license.workspace = true
keywords = ["http", "networking", "smol", "rest-server"]
publish = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.wix]
upgrade-guid = "76DF79DF-E1F9-40A7-89D1-3190562C7851"
path-guid = "FEA82F70-7E57-447F-A361-76FB5E25BA5F"
license = false
eula = false

[features]
default = [
  "http1",
  "http2",
  #"http3",
  "rust-tls"
]

rust-tls = ["futures-rustls", "rustls", "rustls-provider"]

rustls-provider = ["__rustls_awc_lc_rs"]
__rustls_awc_lc_rs = ["futures-rustls/aws-lc-rs", "quinn/rustls-aws-lc-rs"]
__rustls_ring = ["futures-rustls/ring", "quinn/rustls-ring"]

http1 = [
  "hyper/http1",
  "hyper/server",
  "hyper-util/server",
  "hyper-body-utils/generic",
  "hyper-util/http1",
]
http2 = [
  "hyper/http2",
  "hyper/server",
  "hyper-util/server",
  "hyper-body-utils/generic",
  "hyper-util/http2",
]
http3 = [
  "dep:h3",
  "dep:h3-quinn",
  "hyper/server",
  "hyper-util/server",
  "hyper-body-utils/generic",
  "hyper-body-utils/generic-h3",
  "quinn/runtime-smol",
]

[dependencies]
async-lock = { workspace = true }
async-net = "2.0.0"
async-signal = { version = "0.2.12", default-features = false }
base64 = { workspace = true, optional = true }
bytes = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
futures-lite = { workspace = true }
futures-rustls = { workspace = true, optional = true }
futures-util = { workspace = true }
h3 = { workspace = true, optional = true }
h3-quinn = { workspace = true, optional = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, optional = true, default-features = false }
hyper-body-utils = { workspace = true, optional = true, default-features = false }
hyper-util = { workspace = true, optional = true, default-features = false }
log = { workspace = true }
macro_rules_attribute = { version = "0.2.2", default-features = false }
mimalloc = { workspace = true }
peekable = { workspace = true, features = [
  "future",
], default-features = false }
quinn = { workspace = true, optional = true }
radix_trie = { workspace = true }
rand = { workspace = true }
regex = {workspace = true, optional = true }
rustls = { workspace = true, optional = true }
serde = { workspace = true }
serde_yaml_ng = { workspace = true }
signal-hook = { version = "0.4.3", default-features = false }
smol = { version = "2.0.2", default-features = false }
smol-hyper = { version = "0.1.1", default-features = false }
smol-macros = { version = "0.1.1", default-features = false }
socket2 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
typetag = { workspace = true }
url = { workspace = true }
vetis = { workspace = true, default-features = false }

[dev-dependencies]
deboa = { workspace = true }
deboa-smol = { version = "0.1.0", default-features = false, features = [
  "http1",
  "http2",
  #"http3",
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
] }
macro_rules_attribute = { version = "0.2.2", default-features = false }
smol = { version = "2.0.2", default-features = false }
smol-hyper = { version = "0.1.1", default-features = false }
smol-macros = { version = "0.1.1", default-features = false }
vetis-macros = { workspace = true }
